test: single_dynamicstest.cpp dynamics_model.cpp drag.cpp controller.cpp pi.cpp
	c++ single_dynamicstest.cpp dynamics_model.cpp drag.cpp controller.cpp pi.cpp -O3 -o single_dynamicstest

official_test: official_testing.cpp dynamics_model.cpp drag.cpp controller.cpp pi.cpp
	c++ official_testing.cpp dynamics_model.cpp drag.cpp controller.cpp pi.cpp -O3 -o official_test -lwiringPi